apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: api-base
  labels:
    app: api-base
    kube-monkey/enabled: enabled
    kube-monkey/identifier: api-base
    kube-monkey/mtbf: '1'
    kube-monkey/kill-mode: "random-max-percent"
    kube-monkey/kill-value: '75'
spec:
  replicas: 4
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: api-base
  template:
    metadata:
      labels:
        app: api-base
        kube-monkey/enabled: enabled
        kube-monkey/identifier: api-base
      annotations:
        ad.datadoghq.com/api-base.check_names: '["http_check"]'
        ad.datadoghq.com/api-base.init_configs: '[{}]'
        ad.datadoghq.com/api-base.instances: '[{"name": "api-base","url": "https://api-base-namespace.engagedtechnologies.com/swagger/index.html","timeout": 1,"disable_ssl_validation": false,"http_response_status_code": 200}]'
    spec:
      containers:
      - name: api-base
        image: docker.engagedtechnologies.com/api-base:version
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /healthz
            port: 5000
          initialDelaySeconds: 90
          timeoutSeconds: 5
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 5
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /healthz
            port: 5000
          initialDelaySeconds: 60
          timeoutSeconds: 5
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 5
        envFrom:
        - configMapRef:
            name: environment-config
        - secretRef:
            name: api-base-secrets
        env:
        - name: DOGSTATSD_HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
      imagePullSecrets:
      - name: engdockercfg
---
kind: Service
apiVersion: v1
metadata:
  name: api-base
spec:
  selector:
    app: api-base
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: api-base-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: api-base
---
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: api-base-vpa
spec:
  targetRef:
    apiVersion: "apps/v1beta1"
    kind:       Deployment
    name:       api-base
  updatePolicy:
    updateMode: "Auto"
