---
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: api-vpa
spec:
  targetRef:
    apiVersion: "apps/v1beta1"
    kind:       Deployment
    name:       api
  updatePolicy:
    updateMode: "Auto"